import Navbar from "@/components/Navbar";
import "./globals.css";
import Footer from "@/components/Footer";
import { ThemeProvider } from "next-themes";
import Provider from "@/components/Provider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="flex flex-col bg-bgLight dark:bg-bgDark font-custom">
        <Provider>
          <Navbar />
          <main className="flex flex-col flex-1 w-full  ">
            {children}
          </main>
          <Footer />
        </Provider>
      </body>
    </html>
  );
}
