export const dendrogram = {
    name: 'Future of Computing',
    children: [
        {
            topic: 'Environmental Impact of Computing',
            children: [
                { subject: 'Circular Economy' },
                { subject: 'Sustainable development' },
                { subject: 'Climate Change' },
                { subject: 'Mining and Metals' },
                { subject: 'Energy Transition' },
                { subject: 'Electricity' },
                { subject: 'Advanced Materials' },
                { subject: 'Future of the Environment' },
                { subject: 'Artificial Intelligence' },
            ],
        },
        {
            topic: 'Overcoming Technological Limitations',
            children: [
                { subject: 'Quantum Computing' },
                { subject: 'Energy Transition' },
                { subject: 'Innovation' },
                { subject: 'Fourth Industrial Revolution' },
                { subject: 'Biotechnology' },
                { subject: 'Advanced Materials' },
                { subject: 'Trade and Inveestment' },
                { subject: 'Future of the Environment' },
            ],
        },
        {
            topic: 'New Computing Governance Models',
            children: [
                { subject: 'Fourth Industrial Revolution' },
                { subject: 'Digital Identity' },
                { subject: 'European Union' },
                { subject: 'Artificial Intelligence' },
                { subject: 'Corporate Governance' },
                { subject: 'The Digital Economy' },
                { subject: 'Agile Governance' },
                { subject: 'Justice and Law' },
                { subject: 'Internet Governance' },
            ],
        },
        {
            topic: 'Widespread Applications',
            children: [
                { subject: 'Biotechnology' },
                { subject: 'Artificial Intelligence' },
                { subject: 'Precision Medicine' },
                { subject: 'Information and Communications Technology' },
                { subject: 'Retail, Consumer Goods and Lifestyle' },
                { subject: 'Mobility' },
                { subject: '3D Printing' },
                { subject: 'Internet of Things' },
                { subject: 'Health and Healthcare' },
                { subject: 'Future of Consumption' },
                { subject: 'Education' },
            ],
        },
        {
            topic: 'A Broader Computing Reach',
            children: [
                { subject: 'Biotechnology' },
                { subject: 'Advanced Manufacturing' },
                { subject: 'Artificial Intelligence' },
                { subject: 'Precision Medicine' },
                { subject: 'Mobility' },
                { subject: 'Health and Healthcare' },
                { subject: '3D Printing' },
                { subject: 'Virtual and Augumennted Reality' },
                { subject: 'Supply Chains' },
                { subject: 'Automotive Industry' },
            ],
        },
        {
            topic: 'Unlocking Big Data',
            children: [
                { subject: 'Quantum Computing' },
                { subject: 'Digital Identity' },
                { subject: 'Artificial Intelligence' },
                { subject: 'The Digital Economy' },
                { subject: 'Internet Governance' },
                { subject: 'Retail, Consumer Goods and Lifestyle' },
                { subject: 'Internet of Things' },
                { subject: 'Virtual and Augumennted Reality' },
                { subject: 'Media, Entertainment and Sport' },
                { subject: 'Data Science' },
                { subject: 'Human Rights' },
                { subject: 'Behavioural Sciences' },
                { subject: 'Values' },
                { subject: 'Insurance' },
            ],
        },
        {
            topic: 'Cybersecurity Evolution',
            children: [
                { subject: 'Innovation' },
                { subject: 'Fourth Industrial Revolution' },
                { subject: 'Digital Identity' },
                { subject: 'The Digital Economy' },
                { subject: 'Information and Communications Technology' },
                { subject: 'International Security' },
                { subject: 'Cybersecurity' },
                { subject: 'Illicit Economy' },
                { subject: 'Global Risks' },
                { subject: 'Global Governance' },
            ],
        },
    ],
}
